# 389

# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

import collections

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        # if s == "":
        #     return t
        
        # s1 = 0
        # for i in s:
        #     s1 += ord(i)
        # t1 = 0
        # for i in t:
        #     t1 += ord(i)

        # return chr(t1 - s1)        

        if s == "":
            return t
        
        s1 = collections.Counter(s)
        t1 = collections.Counter(t)

        for i in t1:
            if i not in s1 or s1[i] != t1[i]:
                return i
            
            